config/routes.rb
ChulaLounge::Application.routes.draw do

  resources :want_courses
  resources :have_courses
  resources :trade_messages
  resources :trades
  resources :dislikes
  resources :likes

  resources :faculties
  resources :curriculums
  resources :teaches
  resources :courses do
    post 'rate', to: 'courses#rate'
  end
  resources :ratings
  resources :comments do
    post 'like', to: 'comments#like'
    post 'dislike', to: 'comments#dislike'
  end
  resources :professors
  get 'my_trades', to: 'trades#my_trades'
  get 'search_trades', to: 'trades#search'
  
  root :to => "home#index"
  get 'pages/' => 'pages#index'
  post 'save/courses' => 'courses#register'
  post 'save/courses/:id' => 'courses#register_update'
  get 'pages/nav/:id' => 'pages#nav', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }
  get 'pages/nav/:id/course/:cid' => 'pages#course_index', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/, :cid => /[0-9]+(\%7C[0-9]+)*/ }
  get 'pages/course_register' => 'pages#course_register'
  get 'pages/course_register/:id' => 'pages#course_register'
  get 'query/courses' => 'courses#search_query'
  get 'query/curriculums' => 'courses#curriculum_query'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/teach.rb
class Teach < ActiveRecord::Base

	belongs_to :professor
	belongs_to :course

    accepts_nested_attributes_for :professor
	after_create :professor_id, length: {minimum: 1}, numericality: {only_integer: true}, allow_blank: false
	after_create :course_id,  length: {minimum: 1}, numericality: {only_integer: true}, allow_blank: false
	validates :year,  length: {is: 4}, numericality: {only_integer: true}, allow_blank: false
end

app/controllers/teaches_controller.rb
class TeachesController < ApplicationController
  before_action :set_teach, only: [:show, :edit, :update, :destroy]

  # GET /teaches
  # GET /teaches.json
  def index
    @teaches = Teach.all
  end

  # GET /teaches/1
  # GET /teaches/1.json
  def show
  end

  # GET /teaches/new
  def new
    @teach = Teach.new
  end

  # GET /teaches/1/edit
  def edit
  end

  # POST /teaches
  # POST /teaches.json
  def create
    @teach = Teach.new(teach_params)

    respond_to do |format|
      if @teach.save
        format.html { redirect_to @teach, notice: 'Teach was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teach }
      else
        format.html { render action: 'new' }
        format.json { render json: @teach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teaches/1
  # PATCH/PUT /teaches/1.json
  def update
    respond_to do |format|
      if @teach.update(teach_params)
        format.html { redirect_to @teach, notice: 'Teach was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teaches/1
  # DELETE /teaches/1.json
  def destroy
    @teach.destroy
    respond_to do |format|
      format.html { redirect_to teaches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teach
      @teach = Teach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teach_params
      params.require(:teach).permit(:professor_id, :course_id, :year)
    end
end

app/views/teaches/_form.html.erb
<%= form_for(@teach) do |f| %>
  <% if @teach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teach.errors.count, "error") %> prohibited this teach from being saved:</h2>

      <ul>
      <% @teach.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :professor_id %><br>
    <%= f.number_field :professor_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teaches/edit.html.erb
<h1>Editing teach</h1>

<%= render 'form' %>

<%= link_to 'Show', @teach %> |
<%= link_to 'Back', teaches_path %>

app/views/teaches/index.html.erb
<h1>Listing teaches</h1>

<table>
  <thead>
    <tr>
      <th>Professor</th>
      <th>Course</th>
      <th>Year</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teaches.each do |teach| %>
      <tr>
        <td><%= teach.professor_id %></td>
        <td><%= teach.course_id %></td>
        <td><%= teach.year %></td>
        <td><%= link_to 'Show', teach %></td>
        <td><%= link_to 'Edit', edit_teach_path(teach) %></td>
        <td><%= link_to 'Destroy', teach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teach', new_teach_path %>

app/views/teaches/new.html.erb
<h1>New teach</h1>

<%= render 'form' %>

<%= link_to 'Back', teaches_path %>

app/views/teaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professor:</strong>
  <%= @teach.professor_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @teach.course_id %>
</p>

<p>
  <strong>Year:</strong>
  <%= @teach.year %>
</p>

<%= link_to 'Edit', edit_teach_path(@teach) %> |
<%= link_to 'Back', teaches_path %>