config/routes.rb
ChulaLounge::Application.routes.draw do

  resources :want_courses
  resources :have_courses
  resources :trade_messages
  resources :trades
  resources :dislikes
  resources :likes

  resources :faculties
  resources :curriculums
  resources :teaches
  resources :courses do
    post 'rate', to: 'courses#rate'
  end
  resources :ratings
  resources :comments do
    post 'like', to: 'comments#like'
    post 'dislike', to: 'comments#dislike'
  end
  resources :professors
  get 'my_trades', to: 'trades#my_trades'
  get 'search_trades', to: 'trades#search'
  
  root :to => "home#index"
  get 'pages/' => 'pages#index'
  post 'save/courses' => 'courses#register'
  post 'save/courses/:id' => 'courses#register_update'
  get 'pages/nav/:id' => 'pages#nav', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }
  get 'pages/nav/:id/course/:cid' => 'pages#course_index', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/, :cid => /[0-9]+(\%7C[0-9]+)*/ }
  get 'pages/course_register' => 'pages#course_register'
  get 'pages/course_register/:id' => 'pages#course_register'
  get 'query/courses' => 'courses#search_query'
  get 'query/curriculums' => 'courses#curriculum_query'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/controllers/want_courses_controller.rb
class WantCoursesController < ApplicationController
  before_filter :authenticate_user!
  respond_to :json

  def index
    respond_with WantCourse.all
  end
 
  def show
    respond_with WantCourse.find(params[:id])
  end
 
  def create
    respond_with WantCourse.create(params[:want_course])
  end
 
  def update
    respond_with WantCourse.update(params[:id], params[:want_course])
  end
 
  def destroy
    respond_with WantCourse.destroy(params[:id])
  end

end

app/helpers/want_courses_helper.rb
module WantCoursesHelper
end

app/views/want_courses/_form.html.erb
<%= simple_form_for(@want_course) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :course_number %>
    <%= f.input :course_name %>
    <%= f.input :course_section %>
    <%= f.input :trade_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/want_courses/edit.html.erb
<h1>Editing want_course</h1>

<%= render 'form' %>

<%= link_to 'Show', @want_course %> |
<%= link_to 'Back', want_courses_path %>

app/views/want_courses/index.html.erb
<h1>Listing want_courses</h1>

<table>
  <thead>
    <tr>
      <th>Course number</th>
      <th>Course name</th>
      <th>Course section</th>
      <th>Trade</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @want_courses.each do |want_course| %>
      <tr>
        <td><%= want_course.course_number %></td>
        <td><%= want_course.course_name %></td>
        <td><%= want_course.course_section %></td>
        <td><%= want_course.trade_id %></td>
        <td><%= link_to 'Show', want_course %></td>
        <td><%= link_to 'Edit', edit_want_course_path(want_course) %></td>
        <td><%= link_to 'Destroy', want_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Want course', new_want_course_path %>

app/views/want_courses/new.html.erb
<h1>New want_course</h1>

<%= render 'form' %>

<%= link_to 'Back', want_courses_path %>

app/views/want_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course number:</strong>
  <%= @want_course.course_number %>
</p>

<p>
  <strong>Course name:</strong>
  <%= @want_course.course_name %>
</p>

<p>
  <strong>Course section:</strong>
  <%= @want_course.course_section %>
</p>

<p>
  <strong>Trade:</strong>
  <%= @want_course.trade_id %>
</p>

<%= link_to 'Edit', edit_want_course_path(@want_course) %> |
<%= link_to 'Back', want_courses_path %>