config/routes.rb
ChulaLounge::Application.routes.draw do

  resources :want_courses
  resources :have_courses
  resources :trade_messages
  resources :trades
  resources :dislikes
  resources :likes

  resources :faculties
  resources :curriculums
  resources :teaches
  resources :courses do
    post 'rate', to: 'courses#rate'
  end
  resources :ratings
  resources :comments do
    post 'like', to: 'comments#like'
    post 'dislike', to: 'comments#dislike'
  end
  resources :professors
  get 'my_trades', to: 'trades#my_trades'
  get 'search_trades', to: 'trades#search'
  
  root :to => "home#index"
  get 'pages/' => 'pages#index'
  post 'save/courses' => 'courses#register'
  post 'save/courses/:id' => 'courses#register_update'
  get 'pages/nav/:id' => 'pages#nav', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }
  get 'pages/nav/:id/course/:cid' => 'pages#course_index', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/, :cid => /[0-9]+(\%7C[0-9]+)*/ }
  get 'pages/course_register' => 'pages#course_register'
  get 'pages/course_register/:id' => 'pages#course_register'
  get 'query/courses' => 'courses#search_query'
  get 'query/curriculums' => 'courses#curriculum_query'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
	belongs_to :course

	validates_associated :user, :course
	
	validates :know_rating, length: {minimum: 1}, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10}, allow_blank: false
	validates :diff_rating, length: {minimum: 1}, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10}, allow_blank: false
	validates :grade_rating, length: {minimum: 1}, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10}, allow_blank: false
	validates :user, length: {minimum: 1} ,allow_blank: false
	validates :course, length: {minimum: 1}, allow_blank: false
	
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rating }
      else
        format.html { render action: 'new' }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:know_rating, :diff_rating, :grade_rating, :course_id, :user_id)
    end
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :know_rating %><br>
    <%= f.number_field :know_rating %>
  </div>
  <div class="field">
    <%= f.label :diff_rating %><br>
    <%= f.number_field :diff_rating %>
  </div>
  <div class="field">
    <%= f.label :grade_rating %><br>
    <%= f.number_field :grade_rating %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <thead>
    <tr>
      <th>Know rating</th>
      <th>Diff rating</th>
      <th>Grade rating</th>
      <th>Course</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.know_rating %></td>
        <td><%= rating.diff_rating %></td>
        <td><%= rating.grade_rating %></td>
        <td><%= rating.course_id %></td>
        <td><%= rating.user_id %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Know rating:</strong>
  <%= @rating.know_rating %>
</p>

<p>
  <strong>Diff rating:</strong>
  <%= @rating.diff_rating %>
</p>

<p>
  <strong>Grade rating:</strong>
  <%= @rating.grade_rating %>
</p>

<p>
  <strong>Course:</strong>
  <%= @rating.course_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user_id %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>