config/routes.rb
ChulaLounge::Application.routes.draw do

  resources :want_courses
  resources :have_courses
  resources :trade_messages
  resources :trades
  resources :dislikes
  resources :likes

  resources :faculties
  resources :curriculums
  resources :teaches
  resources :courses do
    post 'rate', to: 'courses#rate'
  end
  resources :ratings
  resources :comments do
    post 'like', to: 'comments#like'
    post 'dislike', to: 'comments#dislike'
  end
  resources :professors
  get 'my_trades', to: 'trades#my_trades'
  get 'search_trades', to: 'trades#search'
  
  root :to => "home#index"
  get 'pages/' => 'pages#index'
  post 'save/courses' => 'courses#register'
  post 'save/courses/:id' => 'courses#register_update'
  get 'pages/nav/:id' => 'pages#nav', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }
  get 'pages/nav/:id/course/:cid' => 'pages#course_index', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/, :cid => /[0-9]+(\%7C[0-9]+)*/ }
  get 'pages/course_register' => 'pages#course_register'
  get 'pages/course_register/:id' => 'pages#course_register'
  get 'query/courses' => 'courses#search_query'
  get 'query/curriculums' => 'courses#curriculum_query'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]


# GET /courses
  # GET /courses.json
def index
      @courses = Course.all
 end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @teaches = @course.teaches.group_by &:year
    @m = {}
    @teaches.each do |k,v|
      @m[k] = []
      @teaches[k].each do |i|
        @m[k].push(Professor.find(i.professor_id))
      end
    end

    @teaches = @m

    @comments = @course.comments
    @users = []

    @comments.each do |i|
      c = Comment.find(i.id)   
    end
  end

  def query

  end

  def rate
    @course = Course.find(params[:course_id])

    if user_signed_in?
      @rating = @course.ratings.find_or_initialize_by_user_id(current_user.id)
      
      if @rating.update_attributes({
          :know_rating => rating_params[:know_rating],
          :diff_rating => rating_params[:diff_rating],
          :grade_rating => rating_params[:grade_rating]
        })
        render json: @course.ratings
      else
        render json: @rating.errors, status: :unprocessable_entity 
      end
    else
      head :bad_request
    end
  end


  def search_query
    @courses = Course.autocomplete(params[:f],params[:q])
    
    respond_to do |format|
      format.json { render :query }
    end
  end

  def curriculum_query
     @courses = Course.joins(:curriculums).where("curriculums.id = ? AND year = ? AND semester = ?",
      "#{params[:id]}","#{params[:year]}", "#{params[:semester]}")
    respond_to do |format|
      format.json { render :query}
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST
  def register
    @course = Course.new(course_params)
      ts = []
      params2[:teaches].each do |tc|
        tc[:professors].each do |p|
          t = Teach.new({:year=> tc[:year]})
          t.professor = Professor.find(p[:id])
          ts.push(t)
        end
      end
      cs = []
      params2[:curriculums].each do |c|
        cs.push(Curriculum.find(c[:id]))
      end
      @course.teaches = ts
      @course.curriculums = cs

    respond_to do |format|
      if @course.save
        format.json { render json: @course}
      else
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end

  end
  
  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit!
    end
    def params2
      params.permit!
    end
    def rating_params
      params.require(:rating).permit(:know_rating, :diff_rating, :grade_rating, :course_id, :user_id)
    end
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h3>Courses</h3>
<div class="span8">
<table class="table table-condensed">

  <thead>
    <tr>
      <th>Title</th>
      <th>Number</th>
      <th>Academic year</th>
      <th>Registered</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.number %></td>
        <td><%= course.year %></td>
        <td><%= course.created_at.to_date %></td>
         <td>
          <a href= "/courses/<%=course.id %>/edit" class="btn btn-mini rbtn" type="button">Edit</a>
        </td>
        <td><%= button_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } , class: :'btn btn-mini rbtn' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a  href= "<%= pages_course_register_path %>" class="btn btn-mini rbtn" type="button">New Course</a>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
  
</p>

<p>
  <strong>Number:</strong>
  <%= @course.number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>


<p>
  <strong>Academic year:</strong>
  <%= @course.year %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>